Adds Issue Template for `bug`, `feature`, `config`
Goldorion/Custom-Creative-Tabs pull request #1
Opened 2023-01-14 07:03 UTC by PSGitHubUser1

Same as Title.

2023-01-14 17:14 UTC, Goldorion requested changes

2023-01-14 17:14 UTC, Goldorion commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +     - Linux
Add macOS

2023-01-14 17:14 UTC, Goldorion commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +     - Other (Tell us at the Specifications part)
This is not needed as there are only 3 OS supported by Minecraft and they are Windows, macOS and Linux, the only 3 OS used for computers.

2023-01-14 17:14 UTC, Goldorion commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      If the bug is related to the workspace, always provide a minimal reproducible example workspace, export it to a shareable ZIP file, and attach it to the ticket.
This is a mod... not MCreator.

2023-01-14 17:14 UTC, Goldorion commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +    description: Provide loags [Optional]
loags?

2023-01-14 17:14 UTC, Goldorion commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +description: Create a report to help us improve (search for duplicates first)
Change for something like Request a feature

2023-01-14 17:40 UTC, PSGitHubUser1 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +     - Linux
Okey.

2023-01-14 17:40 UTC, PSGitHubUser1 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +     - Other (Tell us at the Specifications part)
Oh

2023-01-14 17:41 UTC, PSGitHubUser1 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      If the bug is related to the workspace, always provide a minimal reproducible example workspace, export it to a shareable ZIP file, and attach it to the ticket.
OHHH YEA!

2023-01-14 17:41 UTC, PSGitHubUser1 commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +    description: Provide loags [Optional]
Thanks.

2023-01-15 04:40 UTC, PSGitHubUser1 commented
Done!!

2023-01-15 04:41 UTC, closed without merging